#!/bin/zsh

BACKLIGHT="/sys/class/backlight/amdgpu_bl1/brightness"
MAX="/sys/class/backlight/amdgpu_bl1/max_brightness"

SCALE="$(( `cat $MAX` * 1/100 ))"

if [ "$1" = "up" ];
then
  echo $(( $( cat $BACKLIGHT ) + $SCALE )) > $BACKLIGHT
elif [ "$1" = "down" ];
then
  echo $(( $( cat $BACKLIGHT ) - $SCALE )) > $BACKLIGHT
elif [ "$1" = "set" ];
then
  echo "$2" > $BACKLIGHT
elif [ "$1" = "get" ];
then
  cat $BACKLIGHT
else
  echo "Usage: brightness [up | down | get | set \$num]"
fi

