#!/bin/zsh

BACKLIGHT="/sys/class/backlight/amdgpu_bl1/brightness"
MAX="/sys/class/backlight/amdgpu_bl1/max_brightness"

SCALE="$(( `cat $MAX` * 1/100 ))"

if [ "$1" = "up" ];
then
  echo $(( $( cat $BACKLIGHT ) + $SCALE )) > $BACKLIGHT

elif [ "$1" = "down" ];
then
  echo "$(( $( cat $BACKLIGHT ) - $SCALE ))" > $BACKLIGHT

elif [ "$1" = "set" ];
then
  echo "$2" > $BACKLIGHT

elif [ "$1" = "get" ];
then
  cat $BACKLIGHT

elif [ "$1" = "scale" ];
then
  echo "$SCALE"

else
  echo "Usage: brightness [up | down | get | scale | set \$num]"
fi

