#!/bin/bash

case "$1" in
    "Sunday") printf "Minggu";;
    "Monday") printf "Senin";;
    "Tuesday") printf "Selasa";;
    "Wednesday") printf "Rabu";;
    "Thursday") printf "Kamis";;
    "Friday") printf "Jumat";;
    "Saturday") printf "Sabtu";;
    "January") printf "Januari";;
    "February") printf "Februari";;
    "March") printf "Maret";;
    "April") printf "April";;
    "May") printf "Mei";;
    "June") printf "Juni";;
    "July") printf "Juli";;
    "August") printf "Agustus";;
    "September") printf "September";;
    "October") printf "Oktober";;
    "November") printf "November";;
    "December") printf "Desember";;
    *);;
esac

