#!/bin/bash

if [[ -f "Cargo.toml" ]]; then
  echo "> cargo run $@"
  cargo run $@
elif [[ -f "package.json" ]]; then
  echo "> npm run dev $@"
  npm run dev $@
elif [[ `stat index.ts 2> /dev/null` ]]; then
  echo "> bun index.ts"
  bun index.ts $@
elif [[ `stat index.js 2> /dev/null` ]]; then
  echo "> node ."
  node . $@
else
  echo "Could not determine project"
  exit 1
fi

