#!/bin/bash


s=$(find ~/dev/rust-workspace ~/dev/config ~/dev -mindepth 1 -maxdepth 1)
b=''
ds=$(echo "$s" | fzf --layout=reverse)

if [[ -z "$ds" ]]; then

elif [[ -d "$ds" ]]; then
  cd "$ds"
elif [[ -f "$ds" ]]; then
  b=$(basename "$ds")
  ds=$(dirname "$ds")
  cd "$ds"
  vim $b
fi

