#!/bin/bash

t=""
t="$t $HOME/dev/lab"
t="$t $HOME/dev/cloned-repo"
t="$t $HOME/dev/config"
t="$t $HOME/dev/rust"
t="$t $HOME/dev/ui"
t="$t $HOME/dev/works"
t="$t $HOME/dev/stash"
t="$t $HOME/dev/verbatim"
t="$t $HOME/dev"
t="$t $HOME/iot"
t="$t $HOME/android/tauri"

s=$(find $(echo $t) -mindepth 1 -maxdepth 1)
ds=$(echo "$s" | fzf --layout=reverse)

if [[ -z "$ds" ]]; then
  echo "$ds"
elif [[ -d "$ds" ]]; then
  cd "$ds"
elif [[ -f "$ds" ]]; then
  cd $(dirname "$ds")
  vim $(basename "$ds")
fi

