#!/bin/bash

MUT=`pactl get-sink-mute $(pactl get-default-sink) | sed 's/Mute: //' -`
BAT=`cat /sys/class/power_supply/BAT0/capacity`
VOL=`pactl get-sink-volume $(pactl get-default-sink) | awk '{print $5}' | head -n 1`
DAY=`date '+%A'`
MON=`date '+%B'`

if [[ "$MUT" = "yes" ]]; then
    LAWFMWAF="MUTED"
else
    LAWFMWAF="$VOL"
fi

T="/home/deuzo/dev/config/script/date-translate"

echo $LAWFMWAF $BAT% $(date '+%R') $($T $DAY) $(date '+%e') $($T $MON) $(date '+%Y')
