
if [[ -f "$HOME/.no-display" ]]; then

else
  if which Hyprland &> /dev/null; then
    if [[ -z $(ps -A | grep Hyprland) ]]; then
      echo Hyprland Detected
      exec Hyprland -c $HOME/dev/config/hypr/hyprland.conf
    fi
  elif which sway &> /dev/null; then
    if [[ -z $(ps -A | grep sway) ]]; then
      echo sway Detected
      exec sway --config $HOME/dev/config/sway/config
    fi
  elif which startx &> /dev/null; then
    if [[ -z $(ps -A | grep startx) ]]; then
      echo xorg Detected
      exec startx
    fi
  else
    echo no display server available
  fi
fi


