
if which Hyprland &> /dev/null; then
  if [[ -f "/tmp/.no-hypr" ]]; then

  else
    if [[ -z $(ps -A | grep Hyprland) ]]; then
      echo Hyprland Detected
      exec Hyprland -c $HOME/dev/config/hypr/hyprland.conf
    fi
  fi
elif which startx &> /dev/null; then
  if [[ -z $(ps -A | grep startx) ]]; then
    echo xorg Detected
    exec startx
  fi
else
  echo no display server available
fi

