#!/bin/bash

type=$1

# rand=$((1 + $RANDOM % 10))
# fname=
#
# i3lock -i "$HOME/img/bg/hu-bg.png" -t

# Path to the folder containing the background images
BACKGROUND_FOLDER="$HOME/Downloads/bg"

# Get a list of all background images in the folder
background_images=("${BACKGROUND_FOLDER}"/*.png)

# Select a random background image
random_image="${background_images[RANDOM % ${#background_images[@]}]}"

# Call i3lock with the random background image
i3lock -i "${random_image}"
