#!/bin/bash

output_dir="$HOME/img"
filename="ss.jpg"
output_path="$output_dir/$filename"

if [ -e "$output_path" ]; then
  counter=1
  while [ -e "$output_path" ]; do
    filename="ss-$counter.jpg"
    output_path="$output_dir/$filename"
    ((counter++))
  done
fi

sleep .2

import -window root "$output_path"

notify-send "Screenshot taken: $output_path"
